version: "3.0"
services:
  mongo:
    image: mongo:7.0.43-jammy
    restart: on-failure:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh 127.0.0.1:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s    
    volumes:
      - ./data:/data/db
    networks:
      - back-end

  api:
    image: flask-api:1.1
    restart: on-failure:5
    ports:
      - 5000:5000
    networks:
      - back-end
      - front-end
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://127.0.0.1:5000/ || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 30s

volumes:
  db:
networks:
  back-end:
  front-end:
