apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "labels" . | indent 4 }}
  name: {{ .Release.Name }}-flask
  namespace: {{ .Values.namespace }}
spec: 
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels:
      {{- include "labels" . | indent 6}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
#      affinity:
#        podAntiAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - podAffinityTerm:
#              labelSelector:
#                matchLabels:
#                  name: mongodb
#            weight: 1
#        nodeAffinity: -> for when it has more nodes
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.image.name }}
        ports:
        - containerPort: 5000
          name: flask
          protocol: TCP
        resources:
          limits:
            cpu: 750m
            ephemeral-storage: 1Gi
            memory: 768Mi
          requests:
            cpu: 500m
            ephemeral-storage: 50Mi
            memory: 512Mi
        livenessProbe:
          exec:
            command:
            - curl --fail --quiet http://localhost:5000/ || exit 1
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
#        readinessProbe:
#          exec:
#            command:
#            - 
#          failureThreshold: 5
#          initialDelaySeconds: 5
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 5
status: {}
