apiVersion: v1
kind: Service
metadata:
  labels:
    app: app 
  name: flask-service
  namespace: pymongo
spec:
  ports:
  - name: app
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30007
  selector:
    app: app
  type: LoadBalancer
status:
  loadBalancer: {}
