namespace: pymongo
replicaCount: 1
image:
  repository: flask-api 
  pullPolicy: Never
  tag: "1.0"
  name: flask-api

service:
  type: NodePort #Loadbalancer when working with cloud provider 
  port: 80
  targetPort: 5000

# Later - Values that already exist in my manifests but no reason to template rn
#
#      affinity:
#        podAntiAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - podAffinityTerm:
#              labelSelector:
#                matchLabels:
#                  name: mongodb
#            weight: 1
#        nodeAffinity: -> for when it has more nodes
#
#         - containerPort: 5000
#           name: flask
#           protocol: TCP
#
# resources: {}
#   limits:
#             cpu: 750m
#             ephemeral-storage: 1Gi
#             memory: 768Mi
#           requests:
#             cpu: 500m
#             ephemeral-storage: 50Mi
#             memory: 512Mi# 
#
# livenessProbe:
#           exec:
#             command:
#             - curl --fail --quiet http://localhost:5000/ || exit 1
#           failureThreshold: 5
#           initialDelaySeconds: 30
#           periodSeconds: 20
#           successThreshold: 1
#           timeoutSeconds: 10
#
#        readinessProbe:
#            command:
#            -
#          failureThreshold: 5
#          initialDelaySeconds: 5
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 5


autoscaling:
#        readinessProbe:
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
